### ISSUE TITLE
svPre generates several error messages for deformable wall simulation

### ISSUE THREAD

**Issue by ktbolt** [SimVascular/svSolver#35]
I am following the Flow Solver tutorial Example 3 (http://simvascular.github.io/docsFlowSolver.html). When I select **Create Data Files for Simulation** the following warning and error messages are displayed:

_LINE 0017: deformable_wall_vtp mesh-complete/walls_combined.vtp
warning: illegal maxChild (15222)
warning: illegal maxChild (15222)
root= 7611 bottom=15222 array_size=15222

  N=        7695
 ndim=       84141
 maxnz=       84141
 before call nw=       58473
 before call inw=       23085

     initial iterative parameters
     preprocessor and preconditioner parameters
          iparm(12) =              4    (nstore)
          iparm(13) =              0    (iscale)
          iparm(14) =              0    (iperm )
          iparm(15) =              1    (ifact )
          iparm(16) =              0    (lvfill)
          iparm(17) =              0    (ltrunc)
          iparm(18) =              2    (ipropa)
          iparm(19) =             -1    (kblsz )
          iparm(20) =             -1    (nbl2d )
          iparm(21) =              1    (ifctv )
          iparm(22) =              1    (iqlr  )
          iparm(23) =              2    (isymm )
          iparm(24) =              0    (ielim )
          iparm(25) =              1    (ndeg  )
          rparm(13) = 0.00000000D+00    (timfac)
          rparm(14) = 0.00000000D+00    (timtot)
          rparm(15) = 0.35500000D-11    (tol   )
          rparm(16) = 0.00000000D+00    (ainf  )

 ************************************************************
 ****************** f a t a l    e r r o r ******************
 ************************************************************

 routine cgsisrcgsr
 insufficient floating point workspace_

A **fatal error** message seems to be pretty serious but svpre finishes and appends the **displacement.vtp** file to **restart.0.1** anyway.

I am testing this on Ubuntu 16.

**Comment by wgyang** [comment]
Hi Dave,
The fatal error is caused by insufficient floating point workspace needed for the linear solver nspcg. The workspace is allocated before calling the solver. So this error can be avoided by increasing the workspace. In stannspcg.f line 70, nwa can be increased to 5*n+2*itmax instead of 3*n+2*itmax. 
Another issue is the generation of presolver script. The presolver script generated by clicking the button contains an additional command "append_displacements restart.0.1". When the displacement information is available, displacements are written into restart file when "write_restart" is called and then displacement is deallocated. When "write_restart" is followed by "append_displacements", displacement data are appended into the restart file and then deallocate the array resulting in an error of double free. Therefore "append_displacements" and "write_restart" should not be executed at the same time. You can modify the corresponding subroutine for presolver script generation by removing "append_displacements". Let me know if it works.
Thanks,
Weiguang

**Comment by ktbolt** [comment]
@wgyang I'll try the changes you suggested. Thanks!
