### ISSUE TITLE
Using multiple processors on a laptop or workstation does not work

### ISSUE THREAD

**Issue by ktbolt** [SimVascular/svSolver#36]
When running a simulation locally (i.e. on a laptop or workstation) using more than one processor seems to hang the solver. The simulation will spawn multiple processes but this seems to not partition the solution correctly.

Many users try to run simulations locally when learning how to use SimVascular. 

One part of the solution is to remove the GUI widget that sets the number of processors. The other part is to enable the solver to detect if it is running locally on a laptop or workstation.

**Comment by osmsc** [comment]
@ktbolt - what platform?  svSolver runs using MSMPI on Windows under the latest release (2019.01.25) up to 4 procs (didn't test more than that).

**Comment by sitadrost** [comment]
I'm using OpenMPI on MacOS 10.14.2, from the command line I can run svSolver on 4 processors no problem, but it seems to be running the full simulation 4 times instead of distributing the problem over 4 CPUs; it's just as slow as running on one CPU. Might be my lack of experience with SImVascular though, perhaps I've missed something in the presolver part.

**Comment by osmsc** [comment]
Is the solver generating the X_procs-case directory?  If this directory exists and contains results, then the solver has to be running in parallel.  If this directory isn't being created, then it is possible the solver is only running on one thread.

**Comment by ktbolt** [comment]
@sitadrost Your observation is correct, even though there are 4 solver jobs running, they are all executing the full solution.  I am looking into this.

**Comment by ktbolt** [comment]
On OSX svsolver jobs do not start if sv is executed by clicking on it, jobs do start if executing sv from the command line. At least on OSX the solver DOES execute jobs correctly using multiple threads, you can confirm this by looking at the size of the restart files and the simulation completes much faster.

**Comment by sitadrost** [comment]
I haven't tried using multiple threads yet, how do I achieve that (MacOS 10.14.2)? As I mentioned before, running on multiple processors is not faster than running on one processor; there's not much of a difference in the size of the restart files either in that case (3 MB vs 3.8 MB). What sort of difference in size are you talking about?

**Comment by ktbolt** [comment]
I am able to run jobs OK now on Ubuntu, my mpi versions where somehow messed up, removed all mpi installs and then reinstalled. 

@sitadrost I am able to run using multiple threads using mpiexec as usual, **mpiexec -n 4 <program>** on OSX. 

Comparing the restart files (CylinderProject) I see for the single processor job

          555069 Jan 31 14:04 restart.10.1

and for the 4 processor job

          147828 Jan 31 14:03 restart.10.1
          152482 Jan 31 14:03 restart.10.2
          155783 Jan 31 14:03 restart.10.3
          151893 Jan 31 14:03 restart.10.4

so the solver job is being partitioned.

The solver is not able to determine if there is a problem with the **mpi** installation, mpiexec will create 4 copies of svolver but if **mpi** only detects 1 processor then the solver will not partition the job. 

I've attached a simple **mpi** program that you can compile (just type **make**) and execute (run.sh). You should see something like **Hello world from processor <SomeName>, rank 0 out of 4 processors**.

**Comment by sitadrost** [comment]
@ktbolt That looks promising, I'll look into my mpi install (installed it using Homebrew).
Right, sorry, I thought you were talking about multithreading (i.e. on one processor), mpiexec -n 4 is what I used too when I said it didn't work properly.
I can't see the attachment you mention, it does sound useful though, where should I look?

**Comment by sitadrost** [comment]
@ktbolt I checked my mpi installation, reinstalled openmpi 4.0.0, built it from source this time. Also, there turned out to be an old version of mpiexec hiding somewhere on my system. So now I explicitly called the new version of mpiexec, but I still get multiple instances of the full simulation running, and only the restart.10.1 etc. files, instead of the restart.10.1, restart.10.2, etc. that you mention.

The only difference with the new version of mpiexec is that it now seems to correctly identify the number of cores on my system (2).

The output of the svsolver command looks like:

`The process ID for myrank (0) is (29421).


The number of processes is 1.

Solver Input Files listed as below:
------------------------------------

The process ID for myrank (0) is (29422).


The number of processes is 1.

Solver Input Files listed as below:
------------------------------------
 Local Config: solver.inp 
 Local Config: solver.inp 
 Default Input File: Not Setup.

Parameter Values setup as below:
----------------------------------------------
 Default Input File: Not Setup.

Parameter Values setup as below:
----------------------------------------------
 Time Varying Boundary Conditions From File: True Time Varying Boundary Conditions From File: True

 BCT File Type: DAT
 BCT File Type: DAT
 Number of BCT Files: 1
 Number of BCT Files: 1
 BCT Matching Type: Global Node ID
 BCT Matching Type: Global Node ID
 BCT Time Scale Factor: 1.0
 BCT Time Scale Factor: 1.0
 Equation of State: Incompressible
`
... etc. So it indeed looks like svSolver is running two full simulations in parallel.

What version of OpenMPI are you using?

**Comment by ktbolt** [comment]
@sitadrost Sorry, forgot to attach the mpi example code, here it is. 
[mpiexample.tar.gz](https://github.com/SimVascular/svSolver/files/2822375/mpiexample.tar.gz)

**Comment by sitadrost** [comment]
O wait sorry, I was too fast there: running it properly returns
```
>>> size 4
Hello world from processor Air.lan, rank 0 out of 4 processors
>>> size 4
Hello world from processor Air.lan, rank 1 out of 4 processors
>>> size 4
>>> size 4
Hello world from processor Air.lan, rank 3 out of 4 processors
Hello world from processor Air.lan, rank 2 out of 4 processors

```

So now it's counting the number of logical cores apparently

**Comment by ktbolt** [comment]
@sitadrost I have found multiple issues related to launching svsolver jobs on OSX.

1) svsolver is expecting to use mpich on OSX so uninstall openmp and install mpich2. I will add this detail to the SimVascular website.

2) Resolving which **mpiexec** to use is error prone. SimVascular first looks for it in /usr/local/sv/svsolver/<version>/bin but the **mpiexec** there is an incorrect symbolic link to an mpich version in Cellar. If not found then the command defaults to **mpiexec** but this cannot be found, I guess the PATH environment variable is not set.

3) There is no handling of errors when launching a svsolver job so if **mpiexec** can't be found no error message is reported and the user just sees "0% complete". 

The workaround for 2) is to set the **mpiexec** path to /usr/local/bin/mpiexec under the SimVascular **Preferences** menu located under the **SimVascular** icon on the Mac toolbar.

**Comment by sitadrost** [comment]
Great, installing mpich did the trick, I can run a simulation on two cores now. Everyone here thanks for your help!

**Comment by ktbolt** [comment]
@sitadrost Great! 

I will update the SimVascular svSolver install documentation for OSX. I still need to fix CMake to create the correct mpiexec symbolic link on OSX.

**Comment by ktbolt** [comment]
I've made changes to the SimVascular web page to describe what MPI implementation to use, should be on the web site soon.

I've also added code to the Simulations plugin to display the mpiexec and solver binaries used to run a solver job in the Preferences page.

**Comment by rohanshad** [comment]
Ran into this same issue today when testing a simulation on a local workstation. I set the **mpiexec** path to /usr/local/bin/mpiexec and used 'brew link mpich' to relink symlinks. Seems to be working now.

**Comment by ktbolt** [comment]
@rohanshad Good that it's working! I am adding some things to check for MPI versions and make solver simulation errors apparent.

**Comment by ktbolt** [comment]
I've added the display of the mpiexec location and MPI implementation (MPICH or OpenMPI) in the **Preferneces->SimVascular Simulation** panel. I've also added improved error reporting when executing a solver job from SimVascular including checking MPI implementation. This should help users to identify problems with MPI.
