### ISSUE TITLE
broken vtk download link

### ISSUE THREAD

**Issue by nolta** [SimVascular/svSolver#64]
When building with cmake on a centos 7.4 cluster, `make` fails because it can't download the following url:
```
http://simvascular.stanford.edu/downloads/public/svsolver/externals/2019.06/linux/centos/7.6/gnu-6.3/x64/release/2019.11.16/centos.7.6.gnu-6.3.x64.release.2019.11.16.vtk.8.1.1.tar.gz
```

However, the real url appears to be:
```
http://simvascular.stanford.edu/downloads/public/svsolver/externals/2019.06/linux/centos/7.6/gnu/6.3/x64/release/2019.11.16/centos.7.6.gnu.6.3.x64.release.2019.11.16.vtk.8.1.1.tar.gz
```

Looks like `gnu/6.3` and `gnu.6.3` were replaced by `gnu-6.3`?

**Comment by ktbolt** [comment]
@nolta I first checked the CMake code and it looks fine. I then did a build on a CentOS 7 VM and that was downloading VTK with the correct URL.

I'm not sure what might be going on here. You are using the latest svSolver source and are building in an empty build directory?

**Comment by nolta** [comment]
I should have mentioned that i'm using the intel compilers & mpi. With gcc/openmpi the download url is correct.

**Comment by ktbolt** [comment]
The svSolver CMake macro **sv_externals_check_versioning()** sets part of the external download url by trying to match the platform and compiler information on the host with that in the http://simvascular.stanford.edu/downloads/public/svsolver/externals/2019.06/linux/centos/externals_compiler_info.txt file
```
7.6/gnu/6.3/x64/release/2019.11.16
```
The  **sv_externals_check_versioning()**  code is unable to find a match for an Intel compiler and so sets the download directory to the values found in externals_compiler_info.txt file, was using a dash rather than a slash.

I had no idea that **sv_externals_check_versioning()** was setting part of the external download url, too bad is was not named **sv_set_externals_url()**.

@nolta I've fixed the problem in a branch https://github.com/ktbolt/svSolver/tree/broken-vtk-download-link_issue-64. See if that works.

**Comment by nolta** [comment]
Yes, fixed. Thanks.

**Comment by ktbolt** [comment]
Merged into the master branch,
