### ISSUE TITLE
svpre: oscillations / inf's in inflow profile

### ISSUE THREAD

**Issue by mrp089** [SimVascular/svSolver#87]
I'm having issues with svpre smoothing my inflow profile. The initial conditions in both cases are prescribed using
```
read_pressure_velocity_vtu mesh-complete/initial.vtu
```
To check the inflow conditions of the model, I take the `bct.dat` and `bct.vtp` files and integrate the inflow velocities over the inlet area. Then, I compare model inflow-profiles to the original pulsatile inflow-profile I want to prescribe. Here are two different inflows results from svpre using the same model (OSMSC 0111_0001) with identical inflow-profiles and different initial conditions:

1. **Oscillations** with pulsatile inflow and [**non-zero** initial conditions](https://drive.google.com/file/d/1QrJXnjhvMomEW7X0X2ZMZUOuAclmjCxt/view?usp=sharing) (red svpre, green/black prescribed):
![0111_0001_inflow](https://user-images.githubusercontent.com/51269309/98757870-424d1280-2382-11eb-8d9c-74c82f2c2190.png)

2. **inf's** with pulsatile inflow and [**zero** initial conditions](https://drive.google.com/file/d/1bdHeJv7e3j1UCH2F3NdhuOpPCtUKA-VK/view?usp=sharing). From the `bct.dat` file:
```
...
4.313720e-01 1.354850e+00 6.432070e+00 700 63531
inf -inf inf 0.000000e+00
-inf inf -inf 1.001431e-03
inf -inf inf 2.002861e-03
...
```
Case 2 turns into case 1 when prescribing initial conditions with
```
initial_pressure 0
initial_velocity 0.0001 0.0001 0.0001
```
Everything is fine when I prescribe [steady-state inflow](https://drive.google.com/file/d/14R_vnqplsnA3RWfE4UQPrR7ATDlXdR-T/view?usp=sharing). 

@osmsc @ktbolt Do you have an idea why this could be happening? Also, I'm not sure why the initial conditions should have an influence on the inflow profile at all.

**Comment by ktbolt** [comment]
@mrp089 I think the oscillations are caused by the large number of modes you are requesting, from the **0111_0001.svpre** file I see the line`bct_fourier_mode_number 351`. Looking at the svPre code I see that the input data is interpolated to 256 points so you can't have more modes than that. Try `bct_fourier_mode_number 200`.

There are no dependencies in svPre that I can see between the initial conditions and inflow BCs. There may be something screwy going when the solver reads in the bct.dat and the initial restart file, can check later, not strong or brave enough to go into the svsolver code right now.

**Comment by mrp089** [comment]
Thanks! Using only 200 modes works.
