### ISSUE TITLE
Problems building from source in Ubuntu 18.04

### ISSUE THREAD

**Issue by abusomv** [SimVascular/svSolver#91]
Hi,

I am assuming that I'm doing things very wrong but here are my problems trying to build svsolver from the repo.

I just tried to build svsolver on a fresh (and updated) install of ubuntu 18.04. After installing the required packages I've tried doing it with CMake but there's an error at the end. `mypre` and `mypost` seem to be build anyway and run as expected but the compilation fails at this step `Linking CXX executable ../../../bin/svsolver-nompi` with a bunch of `undefined reference` errors, no clue on how to solve this problem.

I've then tried building it with make, it all goes smoothly until you try to run the program, then errors of broken paths appear since the variables of `mypre` and `mypost` still have the `REPLACEME` values. It took me a while to know where and to what values to changes this variables, since there are no pointing tips on the [README-build-linux.txt](https://github.com/SimVascular/svSolver/blob/master/BuildWithMake/README-build-linux.txt)
I finally used the values that I got from the CMake build and some trial and error to fix the path, but it would be great to have some more information on the README.

Thanks,
Arnau

**Comment by ktbolt** [comment]
@abusomv The errors building `svsolver-nompi` are from building with OpenMPI rather than MPICH. The `svsolver-nompi` is not really needed, just run the solver using MPI.

The solver build instructions do need to be cleaned up, on my (long) list of things to do.

Note that it is better to post these kinds of questions to the SV Forum https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=188&pluginname=phpBB so other users can see the problem and the solution.

**Comment by abusomv** [comment]
Thanks for the fast reply!

I will try to make a post it on the SV Forum too so that other users can see the problem :smiley: 

And thanks for your work!
